# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "vvv"
#    ansible.playbook = "provisioning/playbook.yml"
#    ansible.sudo = "true"
#  end


  config.vm.provider "virtualbox" do |v|
	  v.memory = 256
  end

  config.vm.define "testServer1" do |testServer1|
    testServer1.vm.network "private_network", ip: "", virtualbox__intnet: "lan"
    testServer1.vm.hostname = "testServer1"
  end

  config.vm.define "testClient1" do |testClient1|
    testClient1.vm.network "private_network", ip: "", virtualbox__intnet: "lan"
    testClient1.vm.hostname = "testClient1"
  end

  config.vm.define "testServer2" do |testServer2|
    testServer2.vm.network "private_network", ip: "", virtualbox__intnet: "lan"
    testServer2.vm.hostname = "testServer2"
  end
  
  config.vm.define "testClient2" do |testClient2|
    testClient2.vm.network "private_network", ip: "", virtualbox__intnet: "lan"
    testClient2.vm.hostname = "testClient2"
  end
  
  config.vm.define "centralRouter" do |centralRouter|
    centralRouter.vm.network "private_network", ip: "", virtualbox__intnet: "lan-bond"
    centralRouter.vm.network "private_network", ip: "", virtualbox__intnet: "lan-bond"
    centralRouter.vm.network "private_network", ip: "", virtualbox__intnet: "lan"
    centralRouter.vm.hostname = "centralRouter"
  end
  
  config.vm.define "inetRouter" do |inetRouter|
    inetRouter.vm.network "private_network", ip: "", virtualbox__intnet: "lan-bond"
    inetRouter.vm.network "private_network", ip: "", virtualbox__intnet: "lan-bond"
    inetRouter.vm.hostname = "inetRouter"
  end

end
