---

- name: Configuration vlan
  hosts:
    - testServer1
    - testClient1
    - testServer2
    - testClient2
  become: true
  roles:
    - vlan

- name: Configuration lacp
  hosts: 
    - centralRouter
    - inetRouter
  become: true
  roles:
    - lacp
