---
# tasks file for roles/lacp
    
- name: Device ifcfg eth1
  template:
    backup: true
    owner: root
    group: root
    src: ifcfg-eth1.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ device1 }}
  notify: restart network
  
- name: Device ifcfg eth2
  template:
    backup: true
    owner: root
    group: root
    src: ifcfg-eth2.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ device2 }}
  notify: restart network
